services:
  - type: web
    name: alans-arcade
    env: static
    staticPublishPath: .
    buildCommand: ""
    headers:
      - path: /*
        name: Cache-Control
        value: no-cache, no-store, must-revalidate
